import AppKit
import ApplicationServices
import Foundation
import UtterKit

/// Blocking wait (the async top level can't call Thread.sleep directly).
func pause(_ seconds: TimeInterval) { Thread.sleep(forTimeInterval: seconds) }

extension PasteInserter {
    /// Time from starting the paste to ⌘V being handed over (text in the app).
    @MainActor func benchInsert() async -> Double? {
        _ = await insert("benchmark text")
        guard let sent = lastTiming.pasteSentNs else { return nil }
        return Double(sent &- lastTiming.startedNs) / 1_000_000
    }
}

/// AX insertion into the real-AppKit test host (only with an unlocked screen).
func benchAccessibility() -> [String: Any] {
    let host = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("app/.build/arm64-apple-macosx/release/UtterAXHost")
    guard FileManager.default.isExecutableFile(atPath: host.path) else {
        return ["available": false, "reason": "UtterAXHost not built (run `make test` once)"]
    }
    let p = Process()
    p.executableURL = host
    let out = Pipe()
    p.standardOutput = out
    p.standardError = FileHandle.nullDevice
    guard (try? p.run()) != nil else { return ["available": false, "reason": "host did not start"] }
    defer { p.terminate() }
    _ = out.fileHandleForReading.availableData // "READY <pid>"
    let app = AXUIElementCreateApplication(p.processIdentifier)
    func find(_ e: AXUIElement, _ depth: Int = 0) -> AXUIElement? {
        guard depth < 8 else { return nil }
        var role: CFTypeRef?
        AXUIElementCopyAttributeValue(e, kAXRoleAttribute as CFString, &role)
        if role as? String == "AXTextArea" { return e }
        var children: CFTypeRef?
        guard AXUIElementCopyAttributeValue(e, kAXChildrenAttribute as CFString, &children) == .success,
              let list = children as? [AXUIElement] else { return nil }
        return list.lazy.compactMap { find($0, depth + 1) }.first
    }
    var element: AXUIElement?
    for _ in 0..<50 where element == nil {
        element = find(app)
        if element == nil { Thread.sleep(forTimeInterval: 0.05) }
    }
    guard let element else { return ["available": false, "reason": "text view not found"] }
    let field = AXFocusedElement(element: element)
    var times: [Double] = []
    for _ in 0..<10 {
        let t0 = clock_gettime_nsec_np(CLOCK_UPTIME_RAW)
        let result = AccessibilityInserter.insert(" word", into: field)
        let t1 = clock_gettime_nsec_np(CLOCK_UPTIME_RAW)
        if result == .inserted { times.append(Double(t1 - t0) / 1_000_000) }
    }
    return ["available": true, "insert_verified_ms_p50": ((percentile(times, 50) ?? -1) * 10).rounded() / 10, "runs": times.count]
}

// MARK: docs/BENCHMARKS.md

func writeMarkdown(_ r: [String: Any], to url: URL, json: String) throws {
    func d(_ any: Any?) -> String {
        switch any {
        case let x as Double: return x == x.rounded() && abs(x) < 1e9 ? String(Int(x)) : String(x)
        case let x as Int: return String(x)
        case let x as UInt64: return String(x)
        case let x as Bool: return x ? "yes" : "no"
        case let x as String: return x
        default: return "—"
        }
    }
    let machine = r["machine"] as? [String: Any] ?? [:]
    let conditions = r["conditions"] as? [String: Any] ?? [:]
    var md = """
    # Benchmarks

    Generated by `make bench` (`utter-bench`) on \(d(r["date"])), git `\(d(r["git"]))`, \(d(r["runtime"])).
    Raw data: `\(json)`. Every number is measured on this machine. Anything that couldn't be measured says so.

    **Machine:** \(d(machine["cpu"])) (\(d(machine["model"]))), \(d(machine["memory_gb"])) GB, \(d(machine["macos"])).
    **Conditions:** lid closed: \(d(conditions["lid_closed"])), display asleep: \(d(conditions["display_asleep"])), screen locked: \(d(conditions["screen_locked"])).

    ## Models (6 fixture clips × 3 runs, Metal)

    | Model | Load ms | Warm-up ms | RTF (mean) | WER | Peak RSS MB | Model RSS MB | CPU % during inference |
    |---|---|---|---|---|---|---|---|

    """
    for m in r["models"] as? [[String: Any]] ?? [] {
        md += "| \(d(m["name"])) | \(d(m["load_ms"])) | \(d(m["warmup_ms"])) | \(d(m["rtf_mean"])) | \(d(m["wer"])) | \(d(m["peak_rss_mb"])) | \(d(m["model_rss_mb"])) | \(d(m["cpu_percent_during_inference"])) |\n"
    }
    let app = r["app"] as? [String: Any] ?? [:]
    md += "\n## App\n\n"
    if let launches = app["launches"] as? [[String: Any]] {
        md += "| Launch → shortcut ready ms | Launch → model ready ms | Idle RSS MB | Idle CPU % |\n|---|---|---|---|\n"
        for l in launches {
            md += "| \(d(l["launch_to_shortcut_ready_ms"])) | \(d(l["launch_to_model_ready_ms"])) | \(d(l["idle_rss_mb"])) | \(d(l["idle_cpu_percent"])) |\n"
        }
    } else {
        md += "Not measured: \(d(app["reason"])).\n"
    }
    let capture = r["capture"] as? [String: Any] ?? [:]
    md += "\n## Capture start (recorder part of key-down → first audio)\n\n"
    if capture["available"] as? Bool == true {
        md += "Cold start p50 **\(d(capture["cold_p50"])) ms** (\(d((capture["start_to_first_sample_ms_cold"] as? [Double])?.map { String($0) }.joined(separator: ", ")))); "
        md += "with Keep Microphone Ready p50 **\(d(capture["warm_p50"])) ms**.\n"
    } else {
        md += "Not measured this run: \(d(capture["reason"])).\n"
    }
    if let wake = r["idle_wake"] as? [String: Any] {
        let after = (wake["after_idle_ms"] as? [String: Any] ?? [:]).sorted { $0.key.count == $1.key.count ? $0.key < $1.key : $0.key.count < $1.key.count }
            .map { "\($0.key): \(d($0.value)) ms" }.joined(separator: ", ")
        md += "\n## Short utterance after idle (\(d(wake["model"])), \(d(wake["audio_ms"])) ms of audio)\n\nBack to back p50 \(d(wake["back_to_back_ms_p50"])) ms; after idling \(after). Apple silicon lowers CPU/GPU clocks within ~100 ms of idle. A warm-up pass on key-down, a keep-alive pass every 150 ms while recording, and a thread QoS change did not help (each pass itself ran cold), and a 50 ms CPU spin saved ~19 ms at a cost of 50 ms, so none of these is used (PROGRESS.md, M6).\n"
    }
    let text = r["text_pipeline"] as? [String: Any] ?? [:]
    md += "\n## Text pipeline\n\nClean mode with 7 vocabulary terms: short utterance p50 \(d(text["clean_short_ms_p50"])) ms; ~900 words p50 \(d(text["clean_900_words_ms_p50"])) ms.\n"
    let insertion = r["insertion"] as? [String: Any] ?? [:]
    md += "\n## Insertion\n\nPaste path to ⌘V handed over (private pasteboard): p50 \(d(insertion["paste_to_sent_ms_p50"])) ms.\n"
    if let ax = insertion["accessibility"] as? [String: Any] {
        md += ax["available"] as? Bool == true
            ? "Accessibility insert + read-back verification into a real NSTextView: p50 \(d(ax["insert_verified_ms_p50"])) ms.\n"
            : "Accessibility insert not measured this run: \(d(ax["reason"])).\n"
    }
    let dict = r["dictation_from_app_log"] as? [String: Any] ?? [:]
    md += "\n## Real dictations (from the app log)\n\n"
    if (dict["count"] as? Int ?? 0) == 0 {
        md += "No dictations logged yet: live dictation is a human check (PROGRESS.md → Blocked on human).\n"
    } else {
        md += "| Stage | n | p50 ms | p95 ms |\n|---|---|---|---|\n"
        for name in ["event_to_callback_ms", "keydown_to_first_sample_ms", "keydown_to_overlay_ms", "inference_ms", "release_to_transcribed_ms", "release_to_insert_done_ms"] {
            if let s = dict[name] as? [String: Any] { md += "| \(name) | \(d(s["n"])) | \(d(s["p50"])) | \(d(s["p95"])) |\n" }
        }
    }
    try md.write(to: url, atomically: true, encoding: .utf8)
}
