[workspace]
resolver = "2"
members = ["sayless-core", "sayless-cli", "sayless-ffi", "uniffi-bindgen"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.85"

[workspace.dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
hound = "3.5"

[profile.release]
lto = "thin"
codegen-units = 1
debug = "line-tables-only"
panic = "unwind"
