import AppKit
import Carbon.HIToolbox

/// Timing of one insertion, for latency logs (ns, `MonoClock`).
public struct InsertTiming: Sendable {
    public var startedNs: UInt64 = 0
    public var snapshotMs: Double = 0
    public var pasteSentNs: UInt64?
    public var firstReadNs: UInt64?
    public var reads = 0
    public var restoredNs: UInt64?
    public var clipboardReadable = true
    public var clipboardAccess: ClipboardAccess = .allowed
    public var frontmostBundleID: String?
}

public enum InsertOutcome: Equatable, Sendable {
    /// Text was pasted; `receipt` is true if the target app actually read it.
    case pasted(receipt: Bool)
    /// Secure input (password field) is active; nothing was inserted.
    case blockedBySecureInput
    case failed(String)
}

/// Clipboard + ⌘V insertion with a full-fidelity clipboard restore (ADR-006).
///
/// The transcript is published as a pasteboard *promise*; when the target app
/// reads it, AppKit asks our provider for the data — that is the read receipt.
/// After receipts go quiet (or a timeout), the previous clipboard is restored,
/// but only if nobody else has written to the pasteboard in the meantime.
@MainActor
public final class PasteInserter: NSObject, NSPasteboardItemDataProvider {
    public static let transientMarkers = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    /// Triggers the paste in the target app; returns an error message on failure.
    public typealias SendPaste = @MainActor () -> String?

    private let pasteboard: NSPasteboard
    private let reader: PasteboardReading
    private let sendPaste: SendPaste
    private let checkSecureInput: Bool
    /// Pasteboard reads for the snapshot can block on the source app (promised
    /// data), so they run here instead of on the main thread.
    private let snapshotQueue = DispatchQueue(label: "dev.utter.clipboard-snapshot", qos: .userInitiated)
    private let captureInFlight = AtomicFlag()
    private var pendingText = ""
    private var receiptCount = 0
    private var waiter: CheckedContinuation<Void, Never>?
    private var quietTimer: Task<Void, Never>?
    private var timeoutTimer: Task<Void, Never>?

    /// Quiet period after the last read before restoring. Restoring does not
    /// delay the text appearing, so this errs long: a busy target may read the
    /// promise more than once, or read late.
    public var quietPeriod: Duration = .milliseconds(400)
    /// Give up waiting for a read after this long and restore anyway.
    public var receiptTimeout: Duration = .milliseconds(2000)
    /// Put the previous clipboard back after pasting (Settings → Text Insertion).
    /// Off: the transcript stays on the clipboard.
    public var restoreClipboard = true
    /// Longest the clipboard snapshot may take before it is given up on.
    public var snapshotTimeout: TimeInterval = 1.0
    public private(set) var lastTiming = InsertTiming()
    /// The pasteboard this inserter writes to (general in the app, private in tests).
    public var board: NSPasteboard { pasteboard }
    /// Wait after publishing the text and before sending ⌘V (setting "paste delay").
    public var pasteDelay: Duration = .zero
    /// Minimum wait after ⌘V before the clipboard may be restored (setting
    /// "delay after paste", for apps that read the clipboard late).
    public var restoreDelay: Duration = .zero

    public init(pasteboard: NSPasteboard = .general, reader: PasteboardReading? = nil, checkSecureInput: Bool = true,
                sendPaste: @escaping SendPaste = PasteInserter.postCommandV) {
        self.pasteboard = pasteboard
        self.reader = reader ?? pasteboard
        self.checkSecureInput = checkSecureInput
        self.sendPaste = sendPaste
    }

    /// Thread-safe Carbon query; callable from any thread.
    public nonisolated static var secureInputActive: Bool { IsSecureEventInputEnabled() }

    /// The insertion in flight; new insertions wait for it so two dictations
    /// never share the pasteboard promise or restore each other's snapshot.
    private var inFlight: Task<InsertOutcome, Never>?

    public func insert(_ text: String) async -> InsertOutcome {
        let previous = inFlight
        let task = Task { @MainActor [weak self] () -> InsertOutcome in
            _ = await previous?.value
            guard let self else { return .failed("Insertion was cancelled.") }
            return await self.performInsert(text)
        }
        inFlight = task
        return await task.value
    }

    private func performInsert(_ text: String) async -> InsertOutcome {
        lastTiming = InsertTiming(startedNs: MonoClock.nowNs())
        lastTiming.frontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if checkSecureInput && Self.secureInputActive { return .blockedBySecureInput }
        let access = ClipboardAccess.current(for: pasteboard)
        lastTiming.clipboardAccess = access
        let snapshot: PasteboardSnapshot
        if access == .allowed {
            nonisolated(unsafe) let reader = self.reader
            // The owner of promised clipboard data can hang while serving it; past
            // the limit, treat the clipboard as unreadable (never restored).
            let limit = snapshotTimeout
            let busy = captureInFlight
            snapshot = await withCheckedContinuation { continuation in
                // A capture from an earlier dictation is still stuck on a hung
                // owner: don't queue behind it (and wait the full limit again).
                if busy.isSet {
                    Log.info("previous clipboard snapshot still running; treating the clipboard as unreadable")
                    continuation.resume(returning: .unreadable)
                    return
                }
                busy.set(true)
                let once = OnceFlag()
                snapshotQueue.async {
                    let captured = PasteboardSnapshot.capture(from: reader)
                    busy.set(false)
                    if once.claim() { continuation.resume(returning: captured) }
                }
                DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + limit) {
                    if once.claim() {
                        Log.info("clipboard snapshot took longer than \(limit) s; treating it as unreadable")
                        continuation.resume(returning: .unreadable)
                    }
                }
            }
        } else {
            // Reading would raise a macOS alert on every dictation (or is denied):
            // don't read; the transcript is simply left on the clipboard.
            snapshot = .unreadable
        }
        lastTiming.snapshotMs = MonoClock.ms(from: lastTiming.startedNs, to: MonoClock.nowNs())
        lastTiming.clipboardReadable = snapshot.readable
        pendingText = text
        receiptCount = 0

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setDataProvider(self, forTypes: [.string])
        if snapshot.readable {
            // The transcript is only passing through; ask clipboard managers to skip it.
            // If we can't restore, it stays as ordinary clipboard text instead.
            for marker in Self.transientMarkers { item.setData(Data(), forType: marker) }
        }
        guard pasteboard.writeObjects([item]) else {
            snapshot.restore(to: pasteboard)
            return .failed("Could not write to the clipboard.")
        }
        let ourChangeCount = pasteboard.changeCount
        if pasteDelay > .zero { try? await Task.sleep(for: pasteDelay) }

        if let error = sendPaste() {
            restoreIfUnchanged(snapshot, ourChangeCount)
            return .failed(error)
        }
        lastTiming.pasteSentNs = MonoClock.nowNs()

        await waitForReadOrTimeout()
        if restoreDelay > .zero, let sent = lastTiming.pasteSentNs {
            let elapsed = Duration.nanoseconds(Int64(MonoClock.nowNs() - sent))
            if elapsed < restoreDelay { try? await Task.sleep(for: restoreDelay - elapsed) }
        }
        let receipt = receiptCount > 0
        if receipt, restoreClipboard {
            restoreIfUnchanged(snapshot, ourChangeCount)
        } else if receipt {
            leaveTranscriptIfUnchanged(ourChangeCount)
        } else {
            // Nothing read the clipboard, so the text almost certainly did not go
            // in (paste blocked, no text focus, a VM or remote desktop). Keep the
            // transcript on the clipboard rather than restore it away.
            leaveTranscriptIfUnchanged(ourChangeCount)
            Log.info("paste not read by the target within \(receiptTimeout); transcript left on clipboard")
        }
        return .pasted(receipt: receipt)
    }

    /// Resumes when reads have been quiet for `quietPeriod`, or at `receiptTimeout`.
    private func waitForReadOrTimeout() async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            waiter = continuation
            let timeout = receiptTimeout
            timeoutTimer = Task { @MainActor [weak self] in
                guard (try? await Task.sleep(for: timeout)) != nil else { return }
                self?.finishWaiting()
            }
        }
        quietTimer?.cancel()
        quietTimer = nil
        timeoutTimer?.cancel()
        timeoutTimer = nil
    }

    private func finishWaiting() {
        waiter?.resume()
        waiter = nil
    }

    private func noteReceipt() {
        receiptCount += 1
        lastTiming.reads = receiptCount
        if lastTiming.firstReadNs == nil { lastTiming.firstReadNs = MonoClock.nowNs() }
        quietTimer?.cancel()
        let quiet = quietPeriod
        quietTimer = Task { @MainActor [weak self] in
            guard (try? await Task.sleep(for: quiet)) != nil else { return }
            self?.finishWaiting()
        }
    }

    private func restoreIfUnchanged(_ snapshot: PasteboardSnapshot, _ ourChangeCount: Int) {
        guard pasteboard.changeCount == ourChangeCount else {
            Log.info("clipboard changed by someone else during paste; not restoring")
            return
        }
        if snapshot.readable {
            snapshot.restore(to: pasteboard)
            lastTiming.restoredNs = MonoClock.nowNs()
        } else {
            leaveTranscriptIfUnchanged(ourChangeCount)
            Log.info("clipboard not restored (access=\(lastTiming.clipboardAccess)); transcript left on clipboard")
        }
    }

    /// Replaces our promise with the transcript as plain clipboard text (no
    /// transient markers), so it neither vanishes nor serves the next dictation.
    private func leaveTranscriptIfUnchanged(_ ourChangeCount: Int) {
        guard pasteboard.changeCount == ourChangeCount else { return }
        pasteboard.clearContents()
        pasteboard.setString(pendingText, forType: .string)
        lastTiming.restoredNs = MonoClock.nowNs()
    }

    /// Posts ⌘V. Uses the key code that types "v" in the current layout.
    public static func postCommandV() -> String? {
        let keyCode = KeyboardLayout.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else { return "Could not create the paste keystroke." }
        // Explicit flags so a still-held ⌥ from the shortcut does not turn this into ⌥⌘V,
        // and briefly ignore the physical keyboard so a key the user is still
        // releasing cannot merge with the synthetic chord.
        source.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents],
                                                          state: .eventSuppressionStateSuppressionInterval)
        source.localEventsSuppressionInterval = 0.05
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
        return nil
    }

    // MARK: NSPasteboardItemDataProvider

    public nonisolated func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        // AppKit calls data providers on the main thread.
        nonisolated(unsafe) let item = item
        MainActor.assumeIsolated {
            item.setString(pendingText, forType: .string)
            noteReceipt()
        }
    }

    public nonisolated func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}

/// Lets exactly one of several racing callbacks win.
final class OnceFlag: @unchecked Sendable {
    private let lock = NSLock()
    private var claimed = false
    func claim() -> Bool {
        lock.lock(); defer { lock.unlock() }
        if claimed { return false }
        claimed = true
        return true
    }
}

/// A lock-protected Bool shared with the snapshot queue.
final class AtomicFlag: @unchecked Sendable {
    private let lock = NSLock()
    private var value = false
    var isSet: Bool { lock.lock(); defer { lock.unlock() }; return value }
    func set(_ newValue: Bool) { lock.lock(); value = newValue; lock.unlock() }
}
