import AppKit
import Carbon.HIToolbox

public enum InsertOutcome: Equatable, Sendable {
    /// Text was pasted; `receipt` is true if the target app actually read it.
    case pasted(receipt: Bool)
    /// Secure input (password field) is active; nothing was inserted.
    case blockedBySecureInput
    case failed(String)
}

/// Clipboard + ⌘V insertion with a full-fidelity clipboard restore (ADR-006).
///
/// The transcript is published as a pasteboard *promise*; when the target app
/// reads it, AppKit asks our provider for the data — that is the read receipt.
/// After receipts go quiet (or a timeout), the previous clipboard is restored,
/// but only if nobody else has written to the pasteboard in the meantime.
@MainActor
public final class PasteInserter: NSObject, NSPasteboardItemDataProvider {
    public static let transientMarkers = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    private let pasteboard: NSPasteboard
    private let postKeystroke: Bool
    private var pendingText = ""
    private var receiptCount = 0
    private var waiter: CheckedContinuation<Void, Never>?
    private var quietTimer: Task<Void, Never>?
    private var timeoutTimer: Task<Void, Never>?

    /// Quiet period after the last read before restoring.
    public var quietPeriod: Duration = .milliseconds(120)
    /// Give up waiting for a read after this long and restore anyway.
    public var receiptTimeout: Duration = .milliseconds(1500)

    public init(pasteboard: NSPasteboard = .general, postKeystroke: Bool = true) {
        self.pasteboard = pasteboard
        self.postKeystroke = postKeystroke
    }

    public static var secureInputActive: Bool { IsSecureEventInputEnabled() }

    public func insert(_ text: String) async -> InsertOutcome {
        if postKeystroke && Self.secureInputActive { return .blockedBySecureInput }
        let snapshot = PasteboardSnapshot.capture(pasteboard)
        pendingText = text
        receiptCount = 0

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setDataProvider(self, forTypes: [.string])
        for marker in Self.transientMarkers { item.setData(Data(), forType: marker) }
        guard pasteboard.writeObjects([item]) else {
            snapshot.restore(to: pasteboard)
            return .failed("Could not write to the clipboard.")
        }
        let ourChangeCount = pasteboard.changeCount

        if postKeystroke, let error = Self.postCommandV() {
            restoreIfUnchanged(snapshot, ourChangeCount)
            return .failed(error)
        }

        await waitForReadOrTimeout()
        let receipt = receiptCount > 0
        restoreIfUnchanged(snapshot, ourChangeCount)
        return .pasted(receipt: receipt)
    }

    /// Resumes when reads have been quiet for `quietPeriod`, or at `receiptTimeout`.
    private func waitForReadOrTimeout() async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            waiter = continuation
            let timeout = receiptTimeout
            timeoutTimer = Task { @MainActor [weak self] in
                guard (try? await Task.sleep(for: timeout)) != nil else { return }
                self?.finishWaiting()
            }
        }
        quietTimer?.cancel()
        quietTimer = nil
        timeoutTimer?.cancel()
        timeoutTimer = nil
    }

    private func finishWaiting() {
        waiter?.resume()
        waiter = nil
    }

    private func noteReceipt() {
        receiptCount += 1
        quietTimer?.cancel()
        let quiet = quietPeriod
        quietTimer = Task { @MainActor [weak self] in
            guard (try? await Task.sleep(for: quiet)) != nil else { return }
            self?.finishWaiting()
        }
    }

    private func restoreIfUnchanged(_ snapshot: PasteboardSnapshot, _ ourChangeCount: Int) {
        guard pasteboard.changeCount == ourChangeCount else {
            Log.info("clipboard changed by someone else during paste; not restoring")
            return
        }
        snapshot.restore(to: pasteboard)
    }

    /// Posts ⌘V. Uses the key code that types "v" in the current layout.
    static func postCommandV() -> String? {
        let keyCode = KeyboardLayout.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else { return "Could not create the paste keystroke." }
        // Explicit flags so a still-held ⌥ from the shortcut does not turn this into ⌥⌘V.
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
        return nil
    }

    // MARK: NSPasteboardItemDataProvider

    public nonisolated func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        // AppKit calls data providers on the main thread.
        nonisolated(unsafe) let item = item
        MainActor.assumeIsolated {
            item.setString(pendingText, forType: .string)
            noteReceipt()
        }
    }

    public nonisolated func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}
